### ISSUE TITLE
Investigate why psgScanData must be set as unsecure for upload to work

### ISSUE THREAD

**Issue by jmz-b** [somnonetz/snet-plugin#2]
`copla-editor` fails to upload to `psgScanData` objects if the datatype is set as secure, even when logged in as admin.

Figure out why this is and fix it

**Comment by RyanPSullivan7** [comment]
Hi, did this start occurring after an upgrade to 1.7.6 of XNAT? If so it may be due to the permissions regression that can occur during that update. We encountered an issuing with Digital Mammography datatype that we set up. About 3-4 weeks ago we discovered that during the upgrade certain parts of the backend didn't propagate the security permissions; this breaks all plugins, including OHIF viewer. Radiologics created a fix for our production environment and were going to give it to the open source team.

You can try testing this plugin in a fresh XNAT 1.7.6 environment and see if it still occurs. If you can't replicate in a fresh environment then it is likely the same issue.

**Comment by jmz-b** [comment]
@RyanPSullivan7 

Hey Ryan, thanks for the tip, but unfortunately this occurs on a fresh XNAT 1.7.6 install.

To be honest I haven't looked into XNAT's permission system in much detail and the fix for this will probably (hopefully) be something fairly simple once I get round to investigating this properly

**Comment by jmz-b** [comment]
Issue is fixed after upgrading to XNAT 1.8.3
